/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SendRouteImport } from './routes/send'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as PointsRouteImport } from './routes/points'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletIndexRouteImport } from './routes/wallet.index'
import { Route as WalletUnlockRouteImport } from './routes/wallet.unlock'
import { Route as WalletSetupRouteImport } from './routes/wallet.setup'
import { Route as WalletSendRouteImport } from './routes/wallet.send'
import { Route as LegalDisclaimerRouteImport } from './routes/legal.disclaimer'
import { Route as AssetIdRouteImport } from './routes/asset.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsRoute = PointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WalletRoute,
} as any)
const WalletUnlockRoute = WalletUnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => WalletRoute,
} as any)
const WalletSetupRoute = WalletSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => WalletRoute,
} as any)
const WalletSendRoute = WalletSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => WalletRoute,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/legal/disclaimer',
  path: '/legal/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetIdRoute = AssetIdRouteImport.update({
  id: '/asset/$id',
  path: '/asset/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/connect': typeof ConnectRoute
  '/points': typeof PointsRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/asset/$id': typeof AssetIdRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/wallet/send': typeof WalletSendRoute
  '/wallet/setup': typeof WalletSetupRoute
  '/wallet/unlock': typeof WalletUnlockRoute
  '/wallet/': typeof WalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/connect': typeof ConnectRoute
  '/points': typeof PointsRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/asset/$id': typeof AssetIdRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/wallet/send': typeof WalletSendRoute
  '/wallet/setup': typeof WalletSetupRoute
  '/wallet/unlock': typeof WalletUnlockRoute
  '/wallet': typeof WalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/connect': typeof ConnectRoute
  '/points': typeof PointsRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/asset/$id': typeof AssetIdRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/wallet/send': typeof WalletSendRoute
  '/wallet/setup': typeof WalletSetupRoute
  '/wallet/unlock': typeof WalletUnlockRoute
  '/wallet/': typeof WalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/connect'
    | '/points'
    | '/receive'
    | '/send'
    | '/settings'
    | '/wallet'
    | '/asset/$id'
    | '/legal/disclaimer'
    | '/wallet/send'
    | '/wallet/setup'
    | '/wallet/unlock'
    | '/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/connect'
    | '/points'
    | '/receive'
    | '/send'
    | '/settings'
    | '/asset/$id'
    | '/legal/disclaimer'
    | '/wallet/send'
    | '/wallet/setup'
    | '/wallet/unlock'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/connect'
    | '/points'
    | '/receive'
    | '/send'
    | '/settings'
    | '/wallet'
    | '/asset/$id'
    | '/legal/disclaimer'
    | '/wallet/send'
    | '/wallet/setup'
    | '/wallet/unlock'
    | '/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  ConnectRoute: typeof ConnectRoute
  PointsRoute: typeof PointsRoute
  ReceiveRoute: typeof ReceiveRoute
  SendRoute: typeof SendRoute
  SettingsRoute: typeof SettingsRoute
  WalletRoute: typeof WalletRouteWithChildren
  AssetIdRoute: typeof AssetIdRoute
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points': {
      id: '/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof PointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/unlock': {
      id: '/wallet/unlock'
      path: '/unlock'
      fullPath: '/wallet/unlock'
      preLoaderRoute: typeof WalletUnlockRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/setup': {
      id: '/wallet/setup'
      path: '/setup'
      fullPath: '/wallet/setup'
      preLoaderRoute: typeof WalletSetupRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/send': {
      id: '/wallet/send'
      path: '/send'
      fullPath: '/wallet/send'
      preLoaderRoute: typeof WalletSendRouteImport
      parentRoute: typeof WalletRoute
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/legal/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$id': {
      id: '/asset/$id'
      path: '/asset/$id'
      fullPath: '/asset/$id'
      preLoaderRoute: typeof AssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WalletRouteChildren {
  WalletSendRoute: typeof WalletSendRoute
  WalletSetupRoute: typeof WalletSetupRoute
  WalletUnlockRoute: typeof WalletUnlockRoute
  WalletIndexRoute: typeof WalletIndexRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletSendRoute: WalletSendRoute,
  WalletSetupRoute: WalletSetupRoute,
  WalletUnlockRoute: WalletUnlockRoute,
  WalletIndexRoute: WalletIndexRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  ConnectRoute: ConnectRoute,
  PointsRoute: PointsRoute,
  ReceiveRoute: ReceiveRoute,
  SendRoute: SendRoute,
  SettingsRoute: SettingsRoute,
  WalletRoute: WalletRouteWithChildren,
  AssetIdRoute: AssetIdRoute,
  LegalDisclaimerRoute: LegalDisclaimerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
